{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"`internal`"}]}],"kind":"declarations"}],"abstract":[{"text":"Error in internal application.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Logic error, bug, or issue with internal operation, …"}],"variants":[{"paths":["\/documentation\/swifterrorkit\/sourceerrorattribute\/internal"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"`internal`"}],"roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:13SwiftErrorKit06SourceB9AttributeO8internalyA2CmF","modules":[{"name":"SwiftErrorKit"}],"title":"SourceErrorAttribute.internal"},"identifier":{"url":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/internal","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute"]]},"references":{"doc://SwiftErrorKit/documentation/SwiftErrorKit":{"type":"topic","role":"collection","abstract":[{"type":"text","text":"Error attribution and commons."}],"url":"\/documentation\/swifterrorkit","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","kind":"symbol","title":"SwiftErrorKit"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute":{"url":"\/documentation\/swifterrorkit\/sourceerrorattribute","role":"symbol","navigatorTitle":[{"text":"SourceErrorAttribute","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"An error attribute to include information about the high-level component"},{"text":" ","type":"text"},{"text":"in which the error emerged.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SourceErrorAttribute","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute","title":"SourceErrorAttribute"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/internal":{"role":"symbol","abstract":[{"type":"text","text":"Error in internal application."},{"type":"text","text":" "},{"type":"text","text":"Logic error, bug, or issue with internal operation, …"}],"url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/internal","title":"SourceErrorAttribute.internal","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"`internal`","kind":"identifier"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/internal"}}}