{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"`internal`","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swifterrorkit\/sourceerrorattribute\/internal"]}],"abstract":[{"text":"Error in internal application.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Logic error, bug, or issue with internal operation, …"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/internal"},"metadata":{"modules":[{"name":"SwiftErrorKit"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"`internal`"}],"role":"symbol","symbolKind":"case","title":"SourceErrorAttribute.internal","externalID":"s:13SwiftErrorKit06SourceB9AttributeO8internalyA2CmF"},"hierarchy":{"paths":[["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","references":{"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute":{"url":"\/documentation\/swifterrorkit\/sourceerrorattribute","abstract":[{"type":"text","text":"An error attribute to include information about the high-level component"},{"type":"text","text":" "},{"text":"in which the error emerged.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SourceErrorAttribute"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceErrorAttribute"}],"title":"SourceErrorAttribute","role":"symbol"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/internal":{"kind":"symbol","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/internal","type":"topic","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/internal","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"`internal`","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Error in internal application.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Logic error, bug, or issue with internal operation, …"}],"title":"SourceErrorAttribute.internal"},"doc://SwiftErrorKit/documentation/SwiftErrorKit":{"title":"SwiftErrorKit","url":"\/documentation\/swifterrorkit","type":"topic","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","kind":"symbol","abstract":[{"text":"Error attribution and commons.","type":"text"}],"role":"collection"}}}