{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute"]]},"metadata":{"externalID":"s:13SwiftErrorKit06SourceB9AttributeO2ioyA2CmF","title":"SourceErrorAttribute.io","role":"symbol","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"io","kind":"identifier"}],"modules":[{"name":"SwiftErrorKit"}],"symbolKind":"case"},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/io"},"abstract":[{"text":"Communication error.","type":"text"},{"type":"text","text":" "},{"text":"Network outage, connectivity problem, protocol error, …","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swifterrorkit\/sourceerrorattribute\/io"]}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"io","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://SwiftErrorKit/documentation/SwiftErrorKit":{"kind":"symbol","role":"collection","title":"SwiftErrorKit","url":"\/documentation\/swifterrorkit","abstract":[{"type":"text","text":"Error attribution and commons."}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","type":"topic"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute":{"title":"SourceErrorAttribute","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"An error attribute to include information about the high-level component"},{"text":" ","type":"text"},{"type":"text","text":"in which the error emerged."}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceErrorAttribute"}],"navigatorTitle":[{"text":"SourceErrorAttribute","kind":"identifier"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute","url":"\/documentation\/swifterrorkit\/sourceerrorattribute"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/io":{"abstract":[{"type":"text","text":"Communication error."},{"type":"text","text":" "},{"text":"Network outage, connectivity problem, protocol error, …","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/io","role":"symbol","title":"SourceErrorAttribute.io","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"io","kind":"identifier"}],"url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/io"}}}