{"sections":[],"kind":"symbol","metadata":{"title":"SourceErrorAttribute","externalID":"s:13SwiftErrorKit06SourceB9AttributeO","modules":[{"name":"SwiftErrorKit"}],"roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","navigatorTitle":[{"text":"SourceErrorAttribute","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SourceErrorAttribute","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/swifterrorkit\/sourceerrorattribute"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SourceErrorAttribute","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/external","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/input","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/internal","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/io","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/system"]},{"identifiers":["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/typeDescription","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/valueDescription"],"title":"Instance Properties"},{"title":"Default Implementations","identifiers":["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/Equatable-Implementations","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/ErrorAttribute-Implementations","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/RawRepresentable-Implementations"],"generated":true}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/DebugInfoErrorAttribute","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/LocalizationErrorAttribute","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/RankErrorAttribute","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SeverityErrorAttribute","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/TagErrorAttribute","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/TraceErrorAttribute","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/UserLevelErrorAttribute"],"title":"Error attributes in the package"}],"abstract":[{"type":"text","text":"An error attribute to include information about the high-level component"},{"type":"text","text":" "},{"text":"in which the error emerged.","type":"text"}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/ErrorAttribute","doc:\/\/SwiftErrorKit\/SQ","doc:\/\/SwiftErrorKit\/SH","doc:\/\/SwiftErrorKit\/SY"],"type":"conformsTo"}],"identifier":{"url":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute","interfaceLanguage":"swift"},"references":{"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/valueDescription":{"type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/valuedescription","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"valueDescription","kind":"identifier"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/valueDescription","role":"symbol","title":"valueDescription"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/UserLevelErrorAttribute":{"navigatorTitle":[{"text":"UserLevelErrorAttribute","kind":"identifier"}],"url":"\/documentation\/swifterrorkit\/userlevelerrorattribute","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"UserLevelErrorAttribute","kind":"identifier"}],"abstract":[{"text":"An error attribute to express error level from user perspective.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","title":"UserLevelErrorAttribute","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/UserLevelErrorAttribute"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/ErrorAttribute":{"navigatorTitle":[{"text":"ErrorAttribute","kind":"identifier"}],"abstract":[{"type":"text","text":"A type that represents an error attribute."}],"title":"ErrorAttribute","url":"\/documentation\/swifterrorkit\/errorattribute","type":"topic","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/ErrorAttribute","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ErrorAttribute","kind":"identifier"}],"role":"symbol"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/external":{"abstract":[{"text":"“Internal” error in external application.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Third-party API or service failure, unexpected behavior, …"}],"kind":"symbol","title":"SourceErrorAttribute.external","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/external","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/external","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"external"}]},"doc://SwiftErrorKit/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/SwiftErrorKit\/SY","type":"unresolvable"},"doc://SwiftErrorKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/SwiftErrorKit\/SQ","type":"unresolvable"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/input":{"title":"SourceErrorAttribute.input","kind":"symbol","abstract":[{"text":"Error resulting from user interaction or input data problem.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Invalid input data, form submission error, user request error, …"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/input","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"input"}],"url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/input"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/init(rawValue:)":{"url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/init(rawvalue:)","role":"symbol","kind":"symbol","abstract":[],"title":"init(rawValue:)","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"type":"topic"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/internal":{"abstract":[{"type":"text","text":"Error in internal application."},{"type":"text","text":" "},{"text":"Logic error, bug, or issue with internal operation, …","type":"text"}],"kind":"symbol","title":"SourceErrorAttribute.internal","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/internal","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/internal","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"`internal`"}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit/DebugInfoErrorAttribute":{"role":"symbol","title":"DebugInfoErrorAttribute","type":"topic","abstract":[{"text":"An error attribute to include custom debug info.","type":"text"}],"url":"\/documentation\/swifterrorkit\/debuginfoerrorattribute","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/DebugInfoErrorAttribute","navigatorTitle":[{"text":"DebugInfoErrorAttribute","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DebugInfoErrorAttribute"}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit":{"title":"SwiftErrorKit","abstract":[{"text":"Error attribution and commons.","type":"text"}],"kind":"symbol","url":"\/documentation\/swifterrorkit","type":"topic","role":"collection","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/LocalizationErrorAttribute":{"url":"\/documentation\/swifterrorkit\/localizationerrorattribute","abstract":[{"type":"text","text":"An error attribute to provide a localized user message."}],"title":"LocalizationErrorAttribute","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/LocalizationErrorAttribute","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"LocalizationErrorAttribute","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"LocalizationErrorAttribute","kind":"identifier"}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/Equatable-Implementations":{"role":"collectionGroup","abstract":[],"type":"topic","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/Equatable-Implementations","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/equatable-implementations","title":"Equatable Implementations","kind":"article"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/ErrorAttribute-Implementations":{"kind":"article","title":"ErrorAttribute Implementations","type":"topic","role":"collectionGroup","abstract":[],"url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/errorattribute-implementations","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/ErrorAttribute-Implementations"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SeverityErrorAttribute":{"abstract":[{"type":"text","text":"An error attribute to express error severity in your system."}],"url":"\/documentation\/swifterrorkit\/severityerrorattribute","role":"symbol","navigatorTitle":[{"text":"SeverityErrorAttribute","kind":"identifier"}],"type":"topic","title":"SeverityErrorAttribute","kind":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SeverityErrorAttribute","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SeverityErrorAttribute","kind":"identifier"}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/RawRepresentable-Implementations":{"url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/rawrepresentable-implementations","title":"RawRepresentable Implementations","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/RawRepresentable-Implementations","kind":"article","type":"topic","role":"collectionGroup","abstract":[]},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/system":{"type":"topic","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/system","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/system","abstract":[{"text":"Error caused by a system that the process runs on.","type":"text"},{"text":" ","type":"text"},{"text":"Hardware failure, OS-level error, resource exhaustion,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"environment configuration, …"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"system"}],"title":"SourceErrorAttribute.system"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/typeDescription":{"type":"topic","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/typedescription","abstract":[],"kind":"symbol","role":"symbol","title":"typeDescription","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/typeDescription","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeDescription"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://SwiftErrorKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/SwiftErrorKit\/SH","type":"unresolvable"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/io":{"title":"SourceErrorAttribute.io","type":"topic","role":"symbol","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/io","kind":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/io","abstract":[{"type":"text","text":"Communication error."},{"text":" ","type":"text"},{"type":"text","text":"Network outage, connectivity problem, protocol error, …"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"io","kind":"identifier"}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit/TagErrorAttribute":{"title":"TagErrorAttribute","navigatorTitle":[{"kind":"identifier","text":"TagErrorAttribute"}],"type":"topic","url":"\/documentation\/swifterrorkit\/tagerrorattribute","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagErrorAttribute"}],"abstract":[{"text":"An error attribute to assign a tag to an error.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/TagErrorAttribute"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/TraceErrorAttribute":{"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/TraceErrorAttribute","url":"\/documentation\/swifterrorkit\/traceerrorattribute","navigatorTitle":[{"text":"TraceErrorAttribute","kind":"identifier"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TraceErrorAttribute","kind":"identifier"}],"abstract":[{"text":"An error attribute to track a source location.","type":"text"}],"title":"TraceErrorAttribute","role":"symbol","kind":"symbol"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute":{"role":"symbol","abstract":[{"text":"An error attribute to include information about the high-level component","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"in which the error emerged."}],"type":"topic","title":"SourceErrorAttribute","url":"\/documentation\/swifterrorkit\/sourceerrorattribute","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute","navigatorTitle":[{"kind":"identifier","text":"SourceErrorAttribute"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceErrorAttribute","kind":"identifier"}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit/RankErrorAttribute":{"navigatorTitle":[{"kind":"identifier","text":"RankErrorAttribute"}],"title":"RankErrorAttribute","abstract":[{"text":"An error attribute to assign a tracked issue a priority.","type":"text"}],"url":"\/documentation\/swifterrorkit\/rankerrorattribute","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/RankErrorAttribute","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RankErrorAttribute"}],"role":"symbol"}}}