{"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/ErrorAttribute","doc:\/\/SwiftErrorKit\/SQ","doc:\/\/SwiftErrorKit\/SH","doc:\/\/SwiftErrorKit\/SY"],"type":"conformsTo","kind":"relationships"}],"metadata":{"role":"symbol","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SourceErrorAttribute","kind":"identifier"}],"modules":[{"name":"SwiftErrorKit"}],"navigatorTitle":[{"text":"SourceErrorAttribute","kind":"identifier"}],"title":"SourceErrorAttribute","externalID":"s:13SwiftErrorKit06SourceB9AttributeO","roleHeading":"Enumeration"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/external","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/input","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/internal","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/io","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/system"]},{"title":"Initializers","identifiers":["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/typeDescription","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/valueDescription"]},{"generated":true,"identifiers":["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/Equatable-Implementations","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/ErrorAttribute-Implementations","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SourceErrorAttribute"}]}]}],"kind":"symbol","seeAlsoSections":[{"generated":true,"title":"Error attributes in the package","identifiers":["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/DebugInfoErrorAttribute","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/LocalizationErrorAttribute","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/RankErrorAttribute","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SeverityErrorAttribute","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/TagErrorAttribute","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/TraceErrorAttribute","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/UserLevelErrorAttribute"]}],"variants":[{"paths":["\/documentation\/swifterrorkit\/sourceerrorattribute"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit"]]},"identifier":{"url":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An error attribute to include information about the high-level component"},{"type":"text","text":" "},{"type":"text","text":"in which the error emerged."}],"references":{"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/system":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"system"}],"abstract":[{"type":"text","text":"Error caused by a system that the process runs on."},{"type":"text","text":" "},{"type":"text","text":"Hardware failure, OS-level error, resource exhaustion,"},{"text":" ","type":"text"},{"text":"environment configuration, …","type":"text"}],"type":"topic","kind":"symbol","title":"SourceErrorAttribute.system","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/system","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/system"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/ErrorAttribute":{"type":"topic","abstract":[{"type":"text","text":"A type that represents an error attribute."}],"title":"ErrorAttribute","navigatorTitle":[{"text":"ErrorAttribute","kind":"identifier"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/ErrorAttribute","url":"\/documentation\/swifterrorkit\/errorattribute","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorAttribute","kind":"identifier"}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/external":{"kind":"symbol","title":"SourceErrorAttribute.external","type":"topic","abstract":[{"type":"text","text":"“Internal” error in external application."},{"type":"text","text":" "},{"type":"text","text":"Third-party API or service failure, unexpected behavior, …"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"external","kind":"identifier"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/external","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/external"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/valueDescription":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"valueDescription","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/valueDescription","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/valuedescription","title":"valueDescription","abstract":[],"role":"symbol","type":"topic"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/UserLevelErrorAttribute":{"type":"topic","title":"UserLevelErrorAttribute","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/UserLevelErrorAttribute","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserLevelErrorAttribute"}],"url":"\/documentation\/swifterrorkit\/userlevelerrorattribute","navigatorTitle":[{"text":"UserLevelErrorAttribute","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"An error attribute to express error level from user perspective."}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/typeDescription":{"kind":"symbol","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/typedescription","role":"symbol","title":"typeDescription","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/typeDescription","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"typeDescription","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit/DebugInfoErrorAttribute":{"url":"\/documentation\/swifterrorkit\/debuginfoerrorattribute","role":"symbol","type":"topic","abstract":[{"type":"text","text":"An error attribute to include custom debug info."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DebugInfoErrorAttribute","kind":"identifier"}],"navigatorTitle":[{"text":"DebugInfoErrorAttribute","kind":"identifier"}],"title":"DebugInfoErrorAttribute","kind":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/DebugInfoErrorAttribute"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/init(rawValue:)":{"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/init(rawValue:)","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/init(rawvalue:)","type":"topic","title":"init(rawValue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[]},"doc://SwiftErrorKit/documentation/SwiftErrorKit/TraceErrorAttribute":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"TraceErrorAttribute","kind":"identifier"}],"title":"TraceErrorAttribute","abstract":[{"type":"text","text":"An error attribute to track a source location."}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/TraceErrorAttribute","navigatorTitle":[{"text":"TraceErrorAttribute","kind":"identifier"}],"url":"\/documentation\/swifterrorkit\/traceerrorattribute","role":"symbol","kind":"symbol","type":"topic"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/RankErrorAttribute":{"type":"topic","abstract":[{"type":"text","text":"An error attribute to assign a tracked issue a priority."}],"title":"RankErrorAttribute","navigatorTitle":[{"text":"RankErrorAttribute","kind":"identifier"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/RankErrorAttribute","url":"\/documentation\/swifterrorkit\/rankerrorattribute","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RankErrorAttribute"}]},"doc://SwiftErrorKit/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/SwiftErrorKit\/SY"},"doc://SwiftErrorKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/SwiftErrorKit\/SQ"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/io":{"abstract":[{"type":"text","text":"Communication error."},{"type":"text","text":" "},{"text":"Network outage, connectivity problem, protocol error, …","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/io","role":"symbol","title":"SourceErrorAttribute.io","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"io","kind":"identifier"}],"url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/io"},"doc://SwiftErrorKit/documentation/SwiftErrorKit":{"kind":"symbol","role":"collection","title":"SwiftErrorKit","url":"\/documentation\/swifterrorkit","abstract":[{"type":"text","text":"Error attribution and commons."}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","type":"topic"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/RawRepresentable-Implementations":{"url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/rawrepresentable-implementations","abstract":[],"type":"topic","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/RawRepresentable-Implementations","role":"collectionGroup","title":"RawRepresentable Implementations","kind":"article"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/internal":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`internal`"}],"role":"symbol","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/internal","kind":"symbol","abstract":[{"type":"text","text":"Error in internal application."},{"text":" ","type":"text"},{"type":"text","text":"Logic error, bug, or issue with internal operation, …"}],"type":"topic","title":"SourceErrorAttribute.internal","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/internal"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/input":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"input"}],"abstract":[{"text":"Error resulting from user interaction or input data problem.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Invalid input data, form submission error, user request error, …"}],"type":"topic","kind":"symbol","title":"SourceErrorAttribute.input","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/input","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/input"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SeverityErrorAttribute":{"title":"SeverityErrorAttribute","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SeverityErrorAttribute"}],"url":"\/documentation\/swifterrorkit\/severityerrorattribute","kind":"symbol","navigatorTitle":[{"text":"SeverityErrorAttribute","kind":"identifier"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SeverityErrorAttribute","abstract":[{"text":"An error attribute to express error severity in your system.","type":"text"}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/Equatable-Implementations":{"type":"topic","abstract":[],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/Equatable-Implementations","title":"Equatable Implementations","kind":"article","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/equatable-implementations","role":"collectionGroup"},"doc://SwiftErrorKit/SH":{"identifier":"doc:\/\/SwiftErrorKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/LocalizationErrorAttribute":{"type":"topic","abstract":[{"type":"text","text":"An error attribute to provide a localized user message."}],"title":"LocalizationErrorAttribute","navigatorTitle":[{"kind":"identifier","text":"LocalizationErrorAttribute"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/LocalizationErrorAttribute","url":"\/documentation\/swifterrorkit\/localizationerrorattribute","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocalizationErrorAttribute","kind":"identifier"}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute":{"title":"SourceErrorAttribute","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"An error attribute to include information about the high-level component"},{"text":" ","type":"text"},{"type":"text","text":"in which the error emerged."}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceErrorAttribute"}],"navigatorTitle":[{"text":"SourceErrorAttribute","kind":"identifier"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute","url":"\/documentation\/swifterrorkit\/sourceerrorattribute"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/TagErrorAttribute":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"TagErrorAttribute","kind":"identifier"}],"url":"\/documentation\/swifterrorkit\/tagerrorattribute","title":"TagErrorAttribute","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/TagErrorAttribute","role":"symbol","navigatorTitle":[{"text":"TagErrorAttribute","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"An error attribute to assign a tag to an error."}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/ErrorAttribute-Implementations":{"title":"ErrorAttribute Implementations","kind":"article","type":"topic","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/ErrorAttribute-Implementations","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/errorattribute-implementations"}}}